schema { query: Query mutation: Mutation subscription: Subscription }
interface Node { id: ID! }
union Search = User | Article
enum State { ACTIVE INACTIVE }
input Filter { enabled: Boolean = false }
extend type Query { search(filter: Filter): [Node!]! }
