#!/bin/sh
# Sprint 58 F15 q2: run the real ban gate against one isolated missed seed.
set -eu

id=${1:-}
scratch=$(umask 077 && mktemp -d "${TMPDIR:-/tmp}/yew-f15-ban.XXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
repo=$scratch/repo

mkdir -p "$repo/scripts" "$repo/src/fl" "$repo/src/text" \
    "$repo/src/unicode" "$repo/src/syn" "$repo/src/mod/ai" \
    "$repo/src/mod/git" "$repo/src/mod/plug" "$repo/src/ui" \
    "$repo/src/edit" \
    "$repo/tests/unit" "$repo/tests/pty/goldens" "$repo/tests/fuzz" \
    "$repo/tests/perf" "$repo/.github"
cp scripts/bans.sh "$repo/scripts/bans.sh"
printf '%s\n' '#!/bin/sh' 'exit 0' >"$repo/scripts/check-module-shims.sh"
chmod +x "$repo/scripts/check-module-shims.sh"
: >"$repo/Makefile"
: >"$repo/tests/fuzz/oracle.c"
: >"$repo/tests/unit/registry.c"
printf '%s\n' \
    'void base(void)' \
    '{' \
    '    yew_off_to_ccol();' \
    '    yew_ccol_to_off_padded();' \
    '    yew_ccol_shortfall();' \
    '    yew_ccol_max();' \
    '}' >"$repo/src/text/register.c"
printf '%s\n' \
    '/* GENERATED by scripts/gen-unicode-tables from UCD 16.0.0 */' \
    'static const unsigned generated_table[] = { 0U };' \
    >"$repo/src/unicode/tables.c"
printf '%s\n' \
    'C(case01)' 'C(case02)' 'C(case03)' 'C(case04)' \
    'C(case05)' 'C(case06)' 'C(case07)' 'C(case08)' \
    'C(case09)' 'C(case10)' 'C(case11)' 'C(case12)' \
    >"$repo/tests/pty/registry.c"

case $id in
    BASE)
        exec /bin/sh "$repo/scripts/bans.sh"
        ;;
    YEW-F-027)
        printf '%s\n' \
            '#define FL_FORMAT bytebuf_printf' \
            'void seeded(const char *fmt) { FL_FORMAT(out, fmt); }' \
            >"$repo/src/fl/seed.c"
        ;;
    YEW-F-028)
        printf '%s\n' \
            '#define FL_DIE abort' \
            'void seeded(void) { FL_DIE(); }' >"$repo/src/fl/seed.c"
        ;;
    YEW-F-029)
        printf '%s\n' \
            '#define SORT_ROWS qsort' \
            'void seeded(void) { SORT_ROWS(p, n, z, cmp); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-030)
        printf '%s\n' \
            '#define JOIN_(a, b) a ## b' \
            '#define JOIN(a, b) JOIN_(a, b)' \
            'JOIN(__attr''ibute, __)((unused)) static int seeded;' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-031)
        printf '%s\n' \
            '#define JOIN_(a, b) a ## b' \
            '#define JOIN(a, b) JOIN_(a, b)' \
            'JOIN(__attr''ibute, __)((JOIN(constr, uctor))) static void seeded(void) {}' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-032)
        printf '%s\n' \
            '#define JOIN_(a, b) a ## b' \
            '#define JOIN(a, b) JOIN_(a, b)' \
            'void seeded(void) { JOIN(p, threa''d_create)(t, 0, f, 0); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-033)
        printf '%s\n' \
            'const char *seeded = __TIME''STAMP__;' >"$repo/src/seed.c"
        ;;
    YEW-F-034)
        printf '%s\n' \
            '#define MAP_FILE mmap' \
            'void seeded(void) { MAP_FILE(0, n, p, f, d, o); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-035)
        printf '%s\n' \
            '#define ALLOCATE malloc' \
            'void seeded(void) { void *p = ALLOCATE(4); (void)p; }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-036)
        printf '%s\n' \
            'char *seeded(void) { char *p = NULL; return getcwd(p, 0); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-037)
        printf '%s\n' \
            'char *seeded(const char *s) { char *p = NULL; return realpath(s, p); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-038)
        printf '%s\n' \
            'int seeded(wchar_t *w, const char *s, size_t n) { return mbtowc(w, s, n); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-039)
        printf '%s\n' \
            'void *seeded(void *h) { return dlvsym(h, "x", "V1"); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-040)
        printf '%s\n' \
            '#define ERROR_TEXT strerror_r' \
            'void seeded(void) { ERROR_TEXT(e, b, n); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-041)
        printf '%s\n' \
            'void seeded(void) { backtrace_symbols_fd(p, n, fd); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-042)
        printf '%s\n' \
            'int seeded(void) { return getopt_long_only(a, v, o, l, i); }' \
            >"$repo/src/seed.c"
        ;;
    YEW-F-043)
        printf '%s\n' \
            'long \' \
            'double seeded(long \' \
            'double x) { return x; }' >"$repo/src/seed.c"
        ;;
    YEW-F-044)
        rm -f "$repo/scripts/check-module-shims.sh"
        cp scripts/check-module-shims.sh "$repo/scripts/check-module-shims.sh"
        mkdir -p "$repo/src/mod/lsp" "$repo/src/mod/ai"
        : >"$repo/src/mod/lsp/lsp.h"
        : >"$repo/src/mod/lsp/shim.c"
        : >"$repo/src/mod/ai/ai.h"
        : >"$repo/src/mod/ai/shim.c"
        : >"$repo/src/mod/git/git.h"
        : >"$repo/src/mod/git/editor.h"
        : >"$repo/src/mod/git/fussmode.h"
        : >"$repo/src/mod/git/shim.c"
        printf '%s\n' \
            'CmdStatus yew_plug_cmd_seed(CmdCtx *cx);' \
            >"$repo/src/mod/plug/plug.h"
        : >"$repo/src/mod/plug/pkg.h"
        printf '%s\n' \
            'CmdStatus yew_plug_cmd_seed(CmdCtx *cx)' \
            '{' \
            '    (void)cx;' \
            '    return (YEW_CMD_OK);' \
            '}' >"$repo/src/mod/plug/shim.c"
        if /bin/sh "$repo/scripts/check-module-shims.sh" >/dev/null 2>&1; then
            exit 1
        fi
        exit 0
        ;;
    YEW-F-045)
        printf '%s\n' \
            'static const unsigned modifiers[] = { 127995U, 65039U, 8205U };' \
            'unsigned seeded(unsigned cp) { return cp == modifiers[0] ? 2U : 1U; }' \
            >"$repo/src/edit/seed.c"
        ;;
    YEW-F-046)
        printf '%s\n' \
            'static const unsigned foreground = 16711680U;' \
            'unsigned seeded(void) { return foreground; }' \
            >"$repo/src/syn/seed.c"
        ;;
    YEW-F-047)
        printf '%s\n' \
            'unsigned seeded(unsigned cp) { return cp >= 0x1100U ? 2U : 1U; }' \
            >"$repo/src/syn/seed.c"
        ;;
    YEW-F-048)
        printf '%s\n' \
            'int seeded(void) { return posix_openpt(0); }' \
            >"$repo/tests/pty/seed.c"
        ;;
    YEW-F-049)
        printf '%s\n' \
            '#!/bin/sh' \
            'export YEW_PTY_"UPDATE"=1' \
            >"$repo/.github/seed.sh"
        ;;
    YEW-F-050)
        printf '%s\n' \
            'long seeded(int fd, void *p, unsigned long n) { return pread(fd, p, n, 0); }' \
            >"$repo/src/text/piece.c"
        ;;
    YEW-F-051)
        printf '%s\n' \
            'void seeded(Grid *g, Cell blank)' \
            '{' \
            '    size_t x;' \
            '    for (x = 0; x < g->cols; x++) g->cells[x] = blank;' \
            '}' >"$repo/src/ui/shadowdraw.c"
        ;;
    YEW-F-052)
        printf '%s\n' \
            'void seeded(Editor *ed, PaneNode *drawer)' \
            '{' \
            '    PaneNode **slot = &ed->panes.pane_root;' \
            '    *slot = drawer;' \
            '}' >"$repo/src/mod/git/fussmode.c"
        ;;
    YEW-F-053)
        printf '%s\n' \
            'long seeded(void) { return random(); }' \
            >"$repo/tests/fuzz/seed.c"
        ;;
    YEW-F-054)
        printf '%s\n' \
            'void seeded(const char *cmd) { execl("/bin/sh", "sh", "-c", cmd, NULL); }' \
            >"$repo/src/text/seed.c"
        ;;
    YEW-F-055)
        printf '%s\n' \
            'void seeded(Bytebuf *shell, const char *path)' \
            '{' \
            '    bytebuf_append(shell, path, strlen(path));' \
            '}' >"$repo/src/edit/seed.c"
        ;;
    YEW-F-056)
        printf '%s\n' \
            'static const char query[] = "\\033]52;" "?\\a";' \
            'const char *seeded(void) { return query; }' \
            >"$repo/src/term_seed.c"
        ;;
    YEW-F-057)
        printf '%s\n' \
            'int seeded(int fd) { return tcflush(fd, TCIFLUSH); }' \
            >"$repo/src/edit/seed.c"
        ;;
    YEW-F-058)
        printf '%s\n' \
            'void base(void)' \
            '{' \
            '    yew_off_to_ccol(); yew_ccol_to_off_padded();' \
            '    yew_ccol_shortfall(); yew_ccol_max();' \
            '}' \
            'void yew_reg_store_raw(void) { yew_reg_set(regs, name, value); }' \
            >"$repo/src/text/register.c"
        printf '%s\n' \
            'void seeded(void) { yew_reg_store_raw(); }' \
            >"$repo/src/edit/seed.c"
        ;;
    YEW-F-059)
        printf '%s\n' \
            'void yew_opt_store_raw(void) { yew_opt_set(ed, 0, "x", 1, v, err); }' \
            >"$repo/src/edit/option.c"
        printf '%s\n' \
            'void seeded(void) { yew_opt_store_raw(); }' \
            >"$repo/src/edit/seed.c"
        ;;
    YEW-F-060)
        printf '%s\n' \
            'void yew_pkg_git_raw(void) { yew_pkg_git(argv, 1, 1, true, run); }' \
            >"$repo/src/mod/plug/pkg.c"
        printf '%s\n' \
            'void seeded(void) { yew_pkg_git_raw(); }' \
            >"$repo/src/edit/seed.c"
        ;;
    YEW-F-061)
        printf '%s\n' \
            'static const unsigned local_widths[] = { 127995U, 65039U };' \
            'void base(void)' \
            '{' \
            '    yew_off_to_ccol(); yew_ccol_to_off_padded();' \
            '    yew_ccol_shortfall(); yew_ccol_max();' \
            '    if (local_widths[0] != 0U) cell_advance += 2U;' \
            '}' >"$repo/src/text/register.c"
        ;;
    YEW-F-062)
        printf '%s\n' \
            'void base(CellCol cursor, CellCol indent)' \
            '{' \
            '    CellCol goal = { cursor.v + indent.v };' \
            '    yew_off_to_ccol(); yew_ccol_to_off_padded();' \
            '    yew_ccol_shortfall(); yew_ccol_max();' \
            '    (void)goal;' \
            '}' >"$repo/src/text/register.c"
        ;;
    YEW-F-063)
        printf '%s\n' \
            '/* yew_off_to_ccol yew_ccol_to_off_padded */' \
            '/* yew_ccol_shortfall yew_ccol_max */' \
            'void base(void) { local_column_math(); }' \
            >"$repo/src/text/register.c"
        ;;
    YEW-F-064)
        printf '%s\n' \
            'typedef struct ModelPiece {' \
            '    const unsigned char *base;' \
            '    size_t start;' \
            '    size_t length;' \
            '} ModelPiece;' \
            'unsigned char model_byte(const ModelPiece *p, size_t i)' \
            '{' \
            '    return p->base[p->start + i];' \
            '}' >"$repo/tests/fuzz/oracle.c"
        ;;
    YEW-F-065)
        printf '%s\n' \
            '/* GENERATED by scripts/gen-unicode-tables from UCD 16.0.0 */' \
            'static const unsigned generated_table[] = { 99U }; /* hand edited */' \
            >"$repo/src/unicode/tables.c"
        ;;
    YEW-F-066)
        printf '%s\n' \
            'void seeded(void) { _Exit(4); }' >"$repo/src/seed.c"
        ;;
    YEW-F-067)
        printf '%s\n' \
            'void seeded(const char *request_bytes)' \
            '{' \
            '    yew_log(YEW_LOG_INFO, "request bytes: %s", request_bytes);' \
            '}' >"$repo/src/mod/ai/seed.c"
        ;;
    YEW-F-068)
        printf '%s\n' \
            'static void test_orphan(void) {}' \
            >"$repo/tests/unit/test_seed.c"
        ;;
    YEW-F-069)
        rm -f "$repo/tests/pty/registry.c"
        ;;
    YEW-F-070)
        printf '%s\n' \
            'C(case01)' 'C(case02)' 'C(case03)' 'C(case04)' \
            'C(case05)' 'C(case06)' 'C(case07)' 'C(case08)' \
            'C(case09)' 'C(case10)' 'C(case11)' 'C(case12)' \
            'const char *snapshot_name = "missing";' \
            'void seeded(PtyCtx *c) { ptc_snapshot(c, snapshot_name); }' \
            >"$repo/tests/pty/registry.c"
        ;;
    YEW-F-071)
        printf '%s\n' \
            'C(case01)' 'C(case02)' 'C(case03)' 'C(case04)' \
            'C(case05)' 'C(case06)' 'C(case07)' 'C(case08)' \
            'C(case09)' 'C(case10)' 'C(case11)' 'C(case12)' \
            '#if 0' 'C(orphan)' '#endif' \
            >"$repo/tests/pty/registry.c"
        : >"$repo/tests/pty/goldens/orphan.golden"
        ;;
    *)
        printf 'unknown F15 ban probe: %s\n' "$id" >&2
        exit 2
        ;;
esac

# The audit test passes only when the real gate rejects the isolated seed.
# At the Sprint 58 baseline each case above is therefore an expected failure.
if /bin/sh "$repo/scripts/bans.sh" >/dev/null 2>&1; then
    exit 1
fi
exit 0
