#!/bin/sh

set -eu

script_dir=$(CDPATH='' cd "$(dirname "$0")" && pwd)
repo_dir=$(dirname "$script_dir")
tmp=$(umask 077 && mktemp -d "${TMPDIR:-/tmp}/sagitta-bans.XXXXXX")
trap 'rm -rf "$tmp"' EXIT HUP INT TERM

all_files=$tmp/all-files
source_files=$tmp/source-files
non_unicode_files=$tmp/non-unicode-files
ci_files=$tmp/ci-files
pty_files=$tmp/pty-files
piece_files=$tmp/piece-files
deterministic_fuzz_files=$tmp/deterministic-fuzz-files
hits=$tmp/hits
: >"$hits"

find "$repo_dir/src" "$repo_dir/tests" -type f -print |
    LC_ALL=C sort >"$all_files"
find "$repo_dir/src" -type f -print | LC_ALL=C sort >"$source_files"
find "$repo_dir/.github" -type f -print | LC_ALL=C sort >"$ci_files"
{
    find "$repo_dir/tests" -type f -print
    printf '%s\n' "$repo_dir/Makefile"
} | LC_ALL=C sort >"$pty_files"
printf '%s\n' "$repo_dir/src/text/piece.c" >"$piece_files"
find "$repo_dir/tests/fuzz" "$repo_dir/scripts" -type f -print |
    LC_ALL=C sort >"$deterministic_fuzz_files"
while IFS= read -r file; do
    case ${file#"$repo_dir"/} in
        src/unicode/*) ;;
        *) printf '%s\n' "$file" ;;
    esac
done <"$source_files" >"$non_unicode_files"

scan()
{
    label=$1
    pattern=$2
    file_list=$3
    scan_hits=$tmp/scan
    : >"$scan_hits"
    while IFS= read -r file; do
        grep -nE -e "$pattern" "$file" 2>/dev/null |
            sed "s|^|${file#"$repo_dir"/}:|" >>"$scan_hits" || :
    done <"$file_list"
    if [ -s "$scan_hits" ]; then
        echo "ban: $label" >>"$hits"
        cat "$scan_hits" >>"$hits"
    fi
}

scan "qsort is unstable; use sag_sort_stable" \
    '(^|[^[:alnum:]_])qsort[[:space:]]*\(' "$all_files"
scan "__attribute__ is outside the locked C11 subset" \
    '__attribute__' "$all_files"
scan "constructor registration is forbidden; use the explicit registry" \
    'constructor' "$all_files"
scan "threads are forbidden in the single-threaded core" \
    '(threads\.h|pthread)' "$source_files"
scan "__DATE__ and __TIME__ break reproducible builds" \
    '(__DATE__|__TIME__)' "$source_files"
scan "mmap risks SIGBUS after truncation" \
    '(^|[^[:alnum:]_])mmap[[:space:]]*\(' "$source_files"
scan "locale-dependent Unicode APIs are forbidden" \
    '(wcwidth|wcswidth|mbrtowc|wchar\.h|setlocale|iconv)' "$source_files"
scan "Unicode width math belongs only in src/unicode" \
    '(0x1F3FB|0xFE0F|0x200D|EastAsian)' "$non_unicode_files"
scan "pty creation must use the audited posix_openpt harness" \
    '(forkpty|openpty|-lutil)' "$pty_files"
scan "golden updates are forbidden in CI" \
    'SAG_PTY_UPDATE' "$ci_files"
scan "piece tree file I/O belongs to Sprint 8" \
    '(^|[^[:alnum:]_])(open|fopen|read)[[:space:]]*\(' "$piece_files"
scan "generated edit campaigns must use xorshift64*, not libc randomness" \
    '(^|[^[:alnum:]_])rand[[:space:]]*\(|(^|[^[:alnum:]_])srand[[:space:]]*\(|time[[:space:]]*\([[:space:]]*NULL[[:space:]]*\)' \
    "$deterministic_fuzz_files"

if grep -nE 'sag_textbuf_|piece\.h' \
        "$repo_dir/tests/fuzz/oracle.c" >"$tmp/oracle-hits" 2>/dev/null; then
    echo "ban: the text-buffer oracle must remain implementation-independent" \
        >>"$hits"
    sed 's|^|tests/fuzz/oracle.c:|' "$tmp/oracle-hits" >>"$hits"
fi

tables=$repo_dir/src/unicode/tables.c
generated_marker="GENERATED by scripts/gen-unicode-tables from UCD 16.0.0"
if [ ! -f "$tables" ] ||
   ! grep -F "$generated_marker" "$tables" >/dev/null 2>&1; then
    echo "ban: src/unicode/tables.c lacks its generated-file marker" >>"$hits"
fi

# sag_bug is the single audited process-termination site required by the
# exit-code contract.  No other source file may call exit().
exit_hits=$tmp/exit
: >"$exit_hits"
while IFS= read -r file; do
    case ${file#"$repo_dir"/} in
        src/util/log.c) continue ;;
    esac
    grep -nE -e '(^|[^[:alnum:]_])exit[[:space:]]*\(' "$file" 2>/dev/null |
        sed "s|^|${file#"$repo_dir"/}:|" >>"$exit_hits" || :
done <"$source_files"
if [ -s "$exit_hits" ]; then
    echo "ban: exit() is allowed only in src/util/log.c:sag_bug" >>"$hits"
    cat "$exit_hits" >>"$hits"
fi

registry=$repo_dir/tests/unit/registry.c
defs=$tmp/test-defs
: >"$defs"
for file in "$repo_dir"/tests/unit/test_*.c; do
    [ -f "$file" ] || continue
    sed -n 's/^void[[:space:]]\{1,\}test_\([[:alnum:]_]*\)[[:space:]]*(.*/\1/p' "$file" |
        while IFS= read -r name; do
            printf '%s\t%s\n' "${file#"$repo_dir"/}" "$name"
        done >>"$defs"
done
LC_ALL=C sort -o "$defs" "$defs"

while IFS="$(printf '\t')" read -r file name; do
    [ -n "$name" ] || continue
    if [ ! -f "$registry" ] ||
       ! grep -E "T[[:space:]]*\([[:space:]]*${name}[[:space:]]*\)" "$registry" >/dev/null 2>&1; then
        if ! grep -F "ban: unregistered tests" "$hits" >/dev/null 2>&1; then
            echo "ban: unregistered tests" >>"$hits"
        fi
        echo "$file: test_$name" >>"$hits"
    fi
done <"$defs"

pty_registry=$repo_dir/tests/pty/registry.c
golden_dir=$repo_dir/tests/pty/goldens
if [ -f "$pty_registry" ]; then
    pty_cases=$tmp/pty-cases
    golden_refs=$tmp/golden-refs
    sed -n 's/^[[:space:]]*C[[:space:]]*([[:space:]]*\([[:alnum:]_]*\).*/\1/p' \
        "$pty_registry" | LC_ALL=C sort -u >"$pty_cases"
    if [ "$(wc -l <"$pty_cases" | tr -d ' ')" -lt 12 ]; then
        echo "ban: fewer than 12 registered pty cases" >>"$hits"
    fi
    sed -n 's/.*ptc_snapshot[[:space:]]*([^,]*,[[:space:]]*"\([^"]*\)".*/\1/p' \
        "$pty_registry" | LC_ALL=C sort -u >"$golden_refs"
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        if [ ! -f "$golden_dir/$name.golden" ]; then
            echo "ban: referenced pty golden is missing" >>"$hits"
            echo "tests/pty/goldens/$name.golden" >>"$hits"
        fi
    done <"$golden_refs"
    if [ -d "$golden_dir" ]; then
        for file in "$golden_dir"/*.golden; do
            [ -f "$file" ] || continue
            name=$(basename "$file" .golden)
            if ! grep -Fx "$name" "$golden_refs" >/dev/null 2>&1; then
                echo "ban: orphaned pty golden" >>"$hits"
                echo "tests/pty/goldens/$name.golden" >>"$hits"
            fi
        done
    fi
fi

if [ -s "$hits" ]; then
    cat "$hits" >&2
    exit 1
fi

echo "bans: ok"
