#ifndef YEW_SYN_ATTR_H
#define YEW_SYN_ATTR_H

#include "util/base.h"

typedef enum SynAttr {
    YEW_ATTR_TEXT = 0,
    YEW_ATTR_KEYWORD,
    YEW_ATTR_KEYWORD_CONTROL,
    YEW_ATTR_KEYWORD_OP,
    YEW_ATTR_KEYWORD_STORAGE,
    YEW_ATTR_TYPE,
    YEW_ATTR_TYPE_BUILTIN,
    YEW_ATTR_CONSTANT,
    YEW_ATTR_CONSTANT_BUILTIN,
    YEW_ATTR_NUMBER,
    YEW_ATTR_BOOLEAN,
    YEW_ATTR_CHARACTER,
    YEW_ATTR_STRING,
    YEW_ATTR_STRING_ESCAPE,
    YEW_ATTR_STRING_INTERP,
    YEW_ATTR_STRING_SPECIAL,
    YEW_ATTR_COMMENT,
    YEW_ATTR_COMMENT_DOC,
    YEW_ATTR_COMMENT_TODO,
    YEW_ATTR_FUNCTION,
    YEW_ATTR_FUNCTION_BUILTIN,
    YEW_ATTR_FUNCTION_MACRO,
    YEW_ATTR_METHOD,
    YEW_ATTR_VARIABLE,
    YEW_ATTR_VARIABLE_BUILTIN,
    YEW_ATTR_VARIABLE_PARAM,
    YEW_ATTR_VARIABLE_MEMBER,
    YEW_ATTR_NAMESPACE,
    YEW_ATTR_LABEL,
    YEW_ATTR_ATTRIBUTE,
    YEW_ATTR_PREPROC,
    YEW_ATTR_OPERATOR,
    YEW_ATTR_PUNCT,
    YEW_ATTR_PUNCT_BRACKET,
    YEW_ATTR_PUNCT_DELIM,
    YEW_ATTR_TAG,
    YEW_ATTR_TAG_ATTR,
    YEW_ATTR_HEADING,
    YEW_ATTR_LINK,
    YEW_ATTR_EMPHASIS,
    YEW_ATTR_STRONG,
    YEW_ATTR_CODE,
    YEW_ATTR_LIST,
    YEW_ATTR_QUOTE,
    YEW_ATTR_DIFF_ADD,
    YEW_ATTR_DIFF_DEL,
    YEW_ATTR_ERROR,
    YEW_ATTR_WARNING,
    YEW_ATTR_WHITESPACE_SPECIAL,
    YEW_ATTR_MOTION_UNIT,
    YEW_ATTR_MOTION_ARROW,
    YEW_ATTR_MOTION_COUNT,
    YEW_ATTR_MOTION_CMD,
    YEW_ATTR_UI_INVISIBLE,
    YEW_ATTR__COUNT
} SynAttr;

_Static_assert(YEW_ATTR__COUNT <= 64, "attr id must fit 6 bits");
_Static_assert(YEW_ATTR__COUNT == 54, "semantic attr table is closed for 1.0");

#endif
