/* GENERATED by scripts/gen-langtab from the runtime syntax definitions — do not edit;
 * regenerate with 'scripts/gen-langtab > src/syn/langs_gen.c'. */
#include "syn/langs_gen.h"

static const char *const lang_1_extensions[] = {
    "ini",
    "cfg",
    "conf",
    "properties"
};
static const char *const lang_1_filenames[] = {
    ".editorconfig",
    "*.desktop",
    "*.service"
};

const SynLangSeed yew_syn_builtin_langs[] = {
    {
        1U,
        "ini",
        "runtime/syntax/ini.fl",
        lang_1_extensions,
        4U,
        lang_1_filenames,
        3U,
        NULL,
        0U,
        "^\\s*\\[[A-Za-z0-9_.-]+\\]\\s*$",
        0,
        {";", NULL, NULL}
    }
};

const size_t yew_syn_builtin_langs_len =
    sizeof(yew_syn_builtin_langs) / sizeof(yew_syn_builtin_langs[0]);
