/* GENERATED by scripts/gen-langtab from the runtime syntax definitions — do not edit;
 * regenerate with 'scripts/gen-langtab > src/syn/langs_gen.c'. */
#include "syn/langs_gen.h"

static const char *const lang_1_extensions[] = {
    "c",
    "h"
};

static const char *const lang_2_extensions[] = {
    "css"
};

static const char *const lang_3_extensions[] = {
    "fl"
};

static const char *const lang_4_extensions[] = {
    "f90",
    "f95",
    "f03",
    "f08",
    "f18"
};

static const char *const lang_5_extensions[] = {
    "f",
    "for",
    "ftn",
    "fpp"
};

static const char *const lang_6_extensions[] = {
    "go"
};

static const char *const lang_7_extensions[] = {
    "html",
    "htm",
    "xhtml"
};
static const char *const lang_7_filenames[] = {
    "*.html",
    "*.htm"
};

static const char *const lang_8_extensions[] = {
    "ini",
    "cfg",
    "conf",
    "properties"
};
static const char *const lang_8_filenames[] = {
    ".editorconfig",
    "*.desktop",
    "*.service"
};

static const char *const lang_9_extensions[] = {
    "js",
    "mjs",
    "cjs",
    "jsx"
};
static const char *const lang_9_shebangs[] = {
    "node",
    "nodejs"
};

static const char *const lang_10_extensions[] = {
    "json"
};

static const char *const lang_11_extensions[] = {
    "jsonc"
};
static const char *const lang_11_filenames[] = {
    "tsconfig.json",
    "jsconfig.json",
    ".eslintrc.json",
    "devcontainer.json",
    "*.jsonc"
};

static const char *const lang_12_extensions[] = {
    "mk",
    "mak"
};
static const char *const lang_12_filenames[] = {
    "Makefile",
    "makefile",
    "GNUmakefile",
    "*.mk"
};

static const char *const lang_13_extensions[] = {
    "md",
    "markdown",
    "mdown",
    "mkd"
};
static const char *const lang_13_filenames[] = {
    "README",
    "README.*",
    "CHANGELOG",
    "CONTRIBUTING.md"
};

static const char *const lang_14_extensions[] = {
    "py",
    "pyw",
    "pyi"
};
static const char *const lang_14_filenames[] = {
    "SConstruct",
    "SConscript",
    "wscript"
};
static const char *const lang_14_shebangs[] = {
    "python",
    "python2",
    "python3",
    "pypy",
    "pypy3"
};

static const char *const lang_15_extensions[] = {
    "rs"
};

static const char *const lang_16_extensions[] = {
    "sh",
    "bash"
};
static const char *const lang_16_filenames[] = {
    ".bashrc",
    ".bash_profile",
    ".profile",
    "PKGBUILD"
};
static const char *const lang_16_shebangs[] = {
    "sh",
    "bash",
    "dash",
    "ksh"
};

static const char *const lang_17_extensions[] = {
    "toml"
};
static const char *const lang_17_filenames[] = {
    "Cargo.lock",
    "Pipfile",
    "poetry.lock"
};

static const char *const lang_18_extensions[] = {
    "ts",
    "mts",
    "cts",
    "tsx"
};

static const char *const lang_19_extensions[] = {
    "yaml",
    "yml"
};

const SynLangSeed yew_syn_builtin_langs[] = {
    {
        1U,
        "c",
        "runtime/syntax/c.fl",
        lang_1_extensions,
        2U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        20,
        {"//", "/*", "*/"}
    },
    {
        2U,
        "css",
        "runtime/syntax/css.fl",
        lang_2_extensions,
        1U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        0,
        {NULL, "/*", "*/"}
    },
    {
        3U,
        "fletch",
        "runtime/syntax/fletch.fl",
        lang_3_extensions,
        1U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        20,
        {"#", NULL, NULL}
    },
    {
        4U,
        "fortran",
        "runtime/syntax/fortran.fl",
        lang_4_extensions,
        5U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        20,
        {"!", NULL, NULL}
    },
    {
        5U,
        "fortran-fixed",
        "runtime/syntax/fortran_fixed.fl",
        lang_5_extensions,
        4U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        20,
        {"!", NULL, NULL}
    },
    {
        6U,
        "go",
        "runtime/syntax/go.fl",
        lang_6_extensions,
        1U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        0,
        {"//", "/*", "*/"}
    },
    {
        7U,
        "html",
        "runtime/syntax/html.fl",
        lang_7_extensions,
        3U,
        lang_7_filenames,
        2U,
        NULL,
        0U,
        NULL,
        0,
        {NULL, "<!--", "-->"}
    },
    {
        8U,
        "ini",
        "runtime/syntax/ini.fl",
        lang_8_extensions,
        4U,
        lang_8_filenames,
        3U,
        NULL,
        0U,
        "^\\s*\\[[A-Za-z0-9_.-]+\\]\\s*$",
        0,
        {";", NULL, NULL}
    },
    {
        9U,
        "javascript",
        "runtime/syntax/javascript.fl",
        lang_9_extensions,
        4U,
        NULL,
        0U,
        lang_9_shebangs,
        2U,
        NULL,
        0,
        {"//", "/*", "*/"}
    },
    {
        10U,
        "json",
        "runtime/syntax/json.fl",
        lang_10_extensions,
        1U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        0,
        {NULL, NULL, NULL}
    },
    {
        11U,
        "jsonc",
        "runtime/syntax/jsonc.fl",
        lang_11_extensions,
        1U,
        lang_11_filenames,
        5U,
        NULL,
        0U,
        NULL,
        30,
        {"//", "/*", "*/"}
    },
    {
        12U,
        "make",
        "runtime/syntax/make.fl",
        lang_12_extensions,
        2U,
        lang_12_filenames,
        4U,
        NULL,
        0U,
        NULL,
        10,
        {"#", NULL, NULL}
    },
    {
        13U,
        "markdown",
        "runtime/syntax/markdown.fl",
        lang_13_extensions,
        4U,
        lang_13_filenames,
        4U,
        NULL,
        0U,
        NULL,
        0,
        {NULL, "<!--", "-->"}
    },
    {
        14U,
        "python",
        "runtime/syntax/python.fl",
        lang_14_extensions,
        3U,
        lang_14_filenames,
        3U,
        lang_14_shebangs,
        5U,
        NULL,
        20,
        {"#", NULL, NULL}
    },
    {
        15U,
        "rust",
        "runtime/syntax/rust.fl",
        lang_15_extensions,
        1U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        20,
        {"//", "/*", "*/"}
    },
    {
        16U,
        "sh",
        "runtime/syntax/sh.fl",
        lang_16_extensions,
        2U,
        lang_16_filenames,
        4U,
        lang_16_shebangs,
        4U,
        NULL,
        0,
        {"#", NULL, NULL}
    },
    {
        17U,
        "toml",
        "runtime/syntax/toml.fl",
        lang_17_extensions,
        1U,
        lang_17_filenames,
        3U,
        NULL,
        0U,
        NULL,
        10,
        {"#", NULL, NULL}
    },
    {
        18U,
        "typescript",
        "runtime/syntax/typescript.fl",
        lang_18_extensions,
        4U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        10,
        {"//", "/*", "*/"}
    },
    {
        19U,
        "yaml",
        "runtime/syntax/yaml.fl",
        lang_19_extensions,
        2U,
        NULL,
        0U,
        NULL,
        0U,
        NULL,
        10,
        {"#", NULL, NULL}
    }
};

const size_t yew_syn_builtin_langs_len =
    sizeof(yew_syn_builtin_langs) / sizeof(yew_syn_builtin_langs[0]);
