#include "harness.h"
#include "tests.h"

#define T(n) { #n, test_##n }

const SagTest sag_tests[] = {
    T(arena_align),
    T(arena_strdup),
    T(vec_growth),
    T(vec_free_resets),
    T(strmap_order),
    T(strmap_replace_keeps_order),
    T(intern_roundtrip),
    T(intern_id_stability),
    T(sort_stable_ties),
    T(sort_empty),
    T(bytebuf),
    T(bytebuf_binary),
    T(log_capture),
    T(log_levels),
    T(log_bug_prehook),
    T(mod_require_message),
    T(args_parse_version),
    T(args_parse_help),
    T(args_parse_unknown),
    T(args_parse_file),
    T(args_parse_batch),
    T(args_parse_batch_missing),
    T(args_parse_end_options),
    T(harness_assert_once),
    T(harness_filter_selects),
    T(harness_list_order),
    T(harness_failure_isolated),
    T(harness_intentional_failure),
    T(utf8_valid_decode),
    T(utf8_reject_classes),
    T(utf8_truncated_decode),
    T(utf8_incremental_valid),
    T(utf8_incremental_recovery),
    T(utf8_incremental_finish),
    T(utf8_decode_prev),
    T(utf8_encode_edges),
    T(utf8_escape_helpers),
    T(utf8_validate),
    T(utf8_boundaries),
    T(utf8_exhaustive_scalars),
    T(utf8_exhaustive_surrogates),
    T(utf8_exhaustive_short_strings),
    T(grapheme_state_size),
    T(grapheme_ascii),
    T(grapheme_crlf_control),
    T(grapheme_extend_spacing_prepend),
    T(grapheme_hangul),
    T(grapheme_ri_pairs),
    T(grapheme_emoji_zwj),
    T(grapheme_indic_conjunct),
    T(grapheme_invalid_bytes),
    T(grapheme_backward_bound),
    T(grapheme_corpus),
    T(graphemebreaktest_conformance),
    T(width_codepoints),
    T(width_golden),
    T(width_strings),
    T(width_clip),
    T(tty_raw_input_flags),
    T(tty_raw_output_flags),
    T(tty_raw_local_flags),
    T(tty_raw_control_flags),
    T(tty_restore_blob),
    T(tty_probe_modern),
    T(tty_probe_kitty_only),
    T(tty_probe_sync_only),
    T(tty_probe_dumb_deadline),
    T(tty_probe_decrpm_states),
    T(tty_probe_chunking),
    T(tty_probe_pending_interleaved),
    T(tty_probe_ambiguous_prefix),
    T(tty_probe_config),
    T(tty_truecolor),
};

const size_t sag_tests_len = SAG_ARRAY_LEN(sag_tests);

#undef T
