/*
 * Sprint 18.5 §1: the fuzzy scorer and the ranking order.
 *
 * The parity corpus below was generated by an independent transcription
 * of fuss's `fuzzy_match_score`
 * (~/GithubOrgs/FortranGoingOnForty/fuss/src/fuss_main.f90:1755-1851),
 * written from the Fortran rather than from the C port, so these numbers
 * are a differential check and not a screenshot of our own output.  A
 * refactor that drifts the scoring fails here.
 *
 * fuss's 0 means "no match"; our port returns YEW_FZ_NO_MATCH, so a
 * corpus expectation of 0 is mapped on the way in -- except for the one
 * case that proves why the sentinel exists (see the divergence test).
 *
 * SPRINT 26's TESTING STRATEGY NAMES A test_rank.c.  It does not exist,
 * on purpose: Sprint 18.5 pulled §1/§2 forward and its coverage landed
 * here, so every item that file would hold is already below —
 *
 *   `src` selects the directory      test_fuzzy_rank_basename_tier
 *   prefix-basename above fuzzy      test_fuzzy_rank_basename_tier
 *   tie-break determinism            ..._excludes_and_breaks_ties_...
 *   path_mode == false               ..._path_mode_off_scores_the_whole_label
 *   empty pattern, source order      ..._empty_pattern_preserves_source_order
 *   the >= 30-triple parity corpus   test_fuzzy_parity_corpus (38 rows)
 *
 * and the matched-count-equals-the-footer row is a picker claim, tested
 * in test_picker.c.  A second file duplicating these would be two
 * places to update and one place to forget.
 */
#include "harness.h"

#include <stdlib.h>
#include <string.h>

#include "ws/finder.h"

typedef struct FzCase {
    const char *pat;
    const char *text;
    i32 fuss_score; /* 0 == fuss reported no match */
} FzCase;

static void check_case(const FzCase *c)
{
    i32 want = c->fuss_score == 0 ? YEW_FZ_NO_MATCH : c->fuss_score;
    i32 got = yew_fz_score(c->pat, (u32)strlen(c->pat), c->text,
                           (u32)strlen(c->text), NULL);

    YEW_ASSERT_EQ_I64(got, want);
}

void test_fuzzy_parity_corpus(void)
{
    static const FzCase corpus[] = {
        /* command-name shapes */
        {"", "file.write", 1},
        {"file.write", "file.write", 10000},
        {"FILE.WRITE", "file.write", 10000},
        {"file", "file.write", 5000},
        {"fw", "file.write", 536},
        {"fwq", "file.write_quit", 776},
        {"fw", "file.write_quit", 531},
        {"w", "file.write", 240},
        {"wq", "file.write_quit", 480},
        {"q", "quit", 5000},
        {"qf", "quit_force", 536},
        {"pane", "pane.split_h", 5000},
        {"psh", "pane.split_h", 779},
        {"ph", "pane.split_h", 528},
        {"sr", "search.replace", 384},
        {"srep", "search.replace", 680},
        {"xyz", "file.write", 0},
        {"filewrite", "file.write", 2389},
        /* path shapes */
        {"src", "src", 10000},
        {"src", "src/file.c", 5000},
        {"sf", "src/file.c", 537},
        {"sfc", "src/file.c", 783},
        {"uit", "src/ui/tabs.c", 686},
        {"tabs", "src/ui/tabs.c", 987},
        {"tabs.c", "src/ui/tabs.c", 1887},
        {"utc", "src/ui/tabs.c", 731},
        {"cmd", "src/ui/cmdline.c", 379},
        {"cmdline", "src/ui/cmdline.c", 1679},
        {"ui/cmd", "src/ui/cmdline.c", 1884},
        {"README", "README.md", 5000},
        {"readme", "README.md", 5000},
        {"mk", "Makefile", 391},
        {"make", "Makefile", 5000},
        /* greedy first-match, not optimal alignment: pinned deliberately
         * so nobody "improves" it into a DP without re-pinning. */
        {"abc", "axbxc_abc", 489},
        {"abc", "abc_axbxc", 5000},
        /* gap and length penalties visible */
        {"az", "a_very_long_name_ending_in_z", 496},
        {"ae", "abcde", 392},
        {"ac", "abc", 396},
    };
    size_t i;

    for (i = 0U; i < YEW_ARRAY_LEN(corpus); i++)
        check_case(&corpus[i]);
    YEW_ASSERT(YEW_ARRAY_LEN(corpus) >= 30U);
}

void test_fuzzy_table_rows(void)
{
    /* Every row of the scoring table, isolated, with the expected value
     * taken from the same oracle as the corpus. */
    static const FzCase rows[] = {
        {"", "anything", 1},          /* empty pattern            */
        {"abc", "abc", 10000},        /* exact                    */
        {"AbC", "aBc", 10000},        /* exact, case folded       */
        {"ab", "abc", 5000},          /* prefix                   */
        {"AB", "abc", 5000},          /* prefix, case folded      */
        {"b", "ab", 98},              /* matched char + length    */
        {"b", "a_b", 247},            /* + word boundary (+150)   */
        {"ab", "xab", 297},           /* + consecutive run (+100) */
        {"abc", "xabc", 546},         /* run 2 then 3 (+100 +150) */
        {"ac", "abc", 396},           /* + start of text, - gap   */
        {"z", "abc", 0},              /* no match                 */
        {"abcd", "abc", 0},           /* pattern longer than text */
    };
    size_t i;

    for (i = 0U; i < YEW_ARRAY_LEN(rows); i++)
        check_case(&rows[i]);

    /* The +200 start-of-text bonus, isolated as a relationship: "ac"
     * matches at byte 0 and pays one gap; "bc" matches consecutively
     * from byte 1 and pays none. */
    YEW_ASSERT(yew_fz_score("ac", 2U, "abc", 3U, NULL) >
               yew_fz_score("bc", 2U, "abc", 3U, NULL));
    /* The word-boundary bonus, isolated the same way. */
    YEW_ASSERT(yew_fz_score("b", 1U, "a_b", 3U, NULL) >
               yew_fz_score("b", 1U, "axb", 3U, NULL));
    /* The length penalty: the same match in a longer text scores less. */
    YEW_ASSERT(yew_fz_score("b", 1U, "ab", 2U, NULL) >
               yew_fz_score("b", 1U, "abcdef", 6U, NULL));
}

/*
 * fuss returns 0 both for "pattern not exhausted" and for a real match
 * whose bonuses were exactly cancelled by its length penalty, so a
 * genuine match vanishes from the list.  This is the case that proves
 * it, and the reason YEW_FZ_NO_MATCH is INT32_MIN.
 */
void test_fuzzy_no_match_sentinel_is_distinct_from_score_zero(void)
{
    char text[101];
    i32 matched;
    i32 missing;

    (void)memset(text, 'a', 99U);
    text[99] = 'z';
    text[100] = '\0';

    matched = yew_fz_score("z", 1U, text, 100U, NULL);
    missing = yew_fz_score("q", 1U, text, 100U, NULL);

    /* fuss scores both of these 0. */
    YEW_ASSERT_EQ_I64(matched, 0);
    YEW_ASSERT_EQ_I64(missing, YEW_FZ_NO_MATCH);
    YEW_ASSERT(matched != missing);
}

void test_fuzzy_positions_and_cap(void)
{
    FzMatch m;
    char pat[71];
    char text[72];
    u32 i;

    /* Fuzzy match: positions are the matched bytes, ascending. */
    YEW_ASSERT(yew_fz_score("sfc", 3U, "src/file.c", 10U, &m) !=
               YEW_FZ_NO_MATCH);
    YEW_ASSERT_EQ_U64(m.n_pos, 3U);
    /* "src/file.c": s@0, then the first 'f' at 4, then the first 'c'
     * after it -- which is the trailing one at 9, not the 'c' at 2. */
    YEW_ASSERT_EQ_U64(m.pos[0], 0U);
    YEW_ASSERT_EQ_U64(m.pos[1], 4U);
    YEW_ASSERT_EQ_U64(m.pos[2], 9U);

    /* A prefix match returns before the scan, so positions are filled
     * explicitly -- otherwise the most common row in the menu would
     * highlight nothing. */
    YEW_ASSERT_EQ_I64(yew_fz_score("fi", 2U, "file.c", 6U, &m), 5000);
    YEW_ASSERT_EQ_U64(m.n_pos, 2U);
    YEW_ASSERT_EQ_U64(m.pos[0], 0U);
    YEW_ASSERT_EQ_U64(m.pos[1], 1U);

    /* An exact match likewise. */
    YEW_ASSERT_EQ_I64(yew_fz_score("abc", 3U, "abc", 3U, &m), 10000);
    YEW_ASSERT_EQ_U64(m.n_pos, 3U);

    /* No match leaves no stale positions behind. */
    YEW_ASSERT_EQ_I64(yew_fz_score("zz", 2U, "abc", 3U, &m),
                      YEW_FZ_NO_MATCH);
    YEW_ASSERT_EQ_U64(m.n_pos, 0U);

    /* The 64-position cap: 70 matched bytes, 64 recorded, tail
     * unhighlighted and never rescored. */
    (void)memset(pat, 'a', 70U);
    pat[70] = '\0';
    text[0] = 'b';
    (void)memset(text + 1, 'a', 70U);
    text[71] = '\0';
    YEW_ASSERT(yew_fz_score(pat, 70U, text, 71U, &m) != YEW_FZ_NO_MATCH);
    YEW_ASSERT_EQ_U64(m.n_pos, (u64)YEW_FZ_MAX_POS);
    for (i = 1U; i < m.n_pos; i++)
        YEW_ASSERT(m.pos[i] > m.pos[i - 1U]);
}

void test_fuzzy_ascii_fold_only(void)
{
    static const char cyr_upper[] = "\xd0\xa4"; /* U+0424 CYRILLIC EF   */
    static const char cyr_lower[] = "\xd1\x84"; /* U+0444 cyrillic ef   */
    static const char cjk[] = "\xe6\x97\xa5\xe6\x9c\xac"; /* 日本      */

    /* Non-ASCII matches itself exactly ... */
    YEW_ASSERT_EQ_I64(yew_fz_score(cyr_lower, 2U, cyr_lower, 2U, NULL),
                      10000);
    YEW_ASSERT_EQ_I64(yew_fz_score(cjk, 6U, cjk, 6U, NULL), 10000);
    /* ... and is NOT case-folded, because folding it correctly would
     * need a normalization pass on every keystroke.  Pinned, tested,
     * and documented rather than discovered. */
    YEW_ASSERT_EQ_I64(yew_fz_score(cyr_lower, 2U, cyr_upper, 2U, NULL),
                      YEW_FZ_NO_MATCH);
    /* ASCII beside non-ASCII still folds. */
    YEW_ASSERT_EQ_I64(yew_fz_score("A", 1U, "a", 1U, NULL), 10000);
}

void test_fuzzy_rank_basename_tier(void)
{
    static const char *const paths[] = {"src/file.c", "src"};
    static const char *const deep[] = {"tabs/other/deep.c",
                                       "src/ui/tabs.c"};
    FzRanked out[4];
    u32 n;

    /* The case the tier exists for: `src` selects the directory, not a
     * file inside it. */
    n = yew_fz_rank("src", 3U, paths, 2U, true, out);
    YEW_ASSERT_EQ_U64(n, 2U);
    YEW_ASSERT_EQ_U64(out[0].idx, 1U); /* "src" */
    YEW_ASSERT(out[0].score >= YEW_FZ_BASENAME_TIER);
    YEW_ASSERT(out[1].score < YEW_FZ_BASENAME_TIER);

    /* Every prefix-basename match outranks every fuzzy path match. */
    n = yew_fz_rank("tabs", 4U, deep, 2U, true, out);
    YEW_ASSERT_EQ_U64(n, 2U);
    YEW_ASSERT_EQ_U64(out[0].idx, 1U); /* basename "tabs.c" */
    YEW_ASSERT(out[0].score >= YEW_FZ_BASENAME_TIER);
}

void test_fuzzy_rank_path_mode_off_scores_the_whole_label(void)
{
    static const char *const cmds[] = {"file.write", "write"};
    FzRanked out[2];
    u32 n;

    /*
     * A command name is scored WHOLE.  basename() splits on '/', never
     * on '.', so `ed.file.write` is not "write" with a prefix attached
     * -- if it were, every *.write command would tie at the exact-match
     * tier and the menu would order them arbitrarily.
     */
    n = yew_fz_rank("write", 5U, cmds, 2U, false, out);
    YEW_ASSERT_EQ_U64(n, 2U);
    YEW_ASSERT_EQ_U64(out[0].idx, 1U); /* "write", exact */
    YEW_ASSERT(out[0].score >= YEW_FZ_BASENAME_TIER);
    YEW_ASSERT(out[1].score < YEW_FZ_BASENAME_TIER);

    /* path_mode changes nothing for a label with no '/' ... */
    n = yew_fz_rank("write", 5U, cmds, 2U, true, out);
    YEW_ASSERT_EQ_U64(n, 2U);
    YEW_ASSERT_EQ_U64(out[0].idx, 1U);
    YEW_ASSERT(out[1].score < YEW_FZ_BASENAME_TIER);
}

void test_fuzzy_rank_path_mode_changes_ranking_only_for_paths(void)
{
    static const char *const items[] = {"src/write.c"};
    FzRanked out[1];

    /* With a '/' present the two modes genuinely differ: path_mode
     * scores the basename "write.c" (a prefix match, tiered), while
     * label mode scores "src/write.c" whole (fuzzy, untiered). */
    YEW_ASSERT_EQ_U64(yew_fz_rank("write", 5U, items, 1U, true, out), 1U);
    YEW_ASSERT(out[0].score >= YEW_FZ_BASENAME_TIER);

    YEW_ASSERT_EQ_U64(yew_fz_rank("write", 5U, items, 1U, false, out), 1U);
    YEW_ASSERT(out[0].score < YEW_FZ_BASENAME_TIER);
}

void test_fuzzy_rank_excludes_and_breaks_ties_deterministically(void)
{
    static const char *const forward[] = {"bbb", "aaa", "zzz_no", "aab"};
    static const char *const reverse[] = {"aab", "zzz_no", "aaa", "bbb"};
    FzRanked a[4];
    FzRanked b[4];
    u32 na;
    u32 nb;
    u32 i;

    /* Non-matching candidates are excluded, not sorted last: the count
     * has to mean "matches" for the footer to be honest. */
    na = yew_fz_rank("a", 1U, forward, 4U, false, a);
    YEW_ASSERT_EQ_U64(na, 2U);
    for (i = 0U; i < na; i++)
        YEW_ASSERT(strcmp(forward[a[i].idx], "zzz_no") != 0);

    /* Same set, permuted input, identical output order. */
    nb = yew_fz_rank("a", 1U, reverse, 4U, false, b);
    YEW_ASSERT_EQ_U64(nb, na);
    for (i = 0U; i < na; i++)
        YEW_ASSERT_EQ_STR(forward[a[i].idx], reverse[b[i].idx]);

    /* "aaa" is a prefix match (tiered); "aab" is too.  Equal scores, so
     * the tie breaks by shorter-then-memcmp -- both are length 3, so
     * memcmp decides and "aaa" precedes "aab". */
    YEW_ASSERT_EQ_STR(forward[a[0].idx], "aaa");
    YEW_ASSERT_EQ_STR(forward[a[1].idx], "aab");
}

void test_fuzzy_rank_positions_are_relative_to_the_full_text(void)
{
    static const char *const paths[] = {"src/ui/tabs.c"};
    FzRanked out[1];
    u32 n;

    /* The basename key won, but the renderer draws the whole path, so
     * the positions it gets must index the whole path. */
    n = yew_fz_rank("tabs", 4U, paths, 1U, true, out);
    YEW_ASSERT_EQ_U64(n, 1U);
    YEW_ASSERT_EQ_U64(out[0].m.n_pos, 4U);
    YEW_ASSERT_EQ_U64(out[0].m.pos[0], 7U); /* "src/ui/" is 7 bytes */
    YEW_ASSERT_EQ_U64(out[0].m.pos[3], 10U);
}

void test_fuzzy_rank_directory_basename_ignores_trailing_slash(void)
{
    static const char *const entries[] = {"archive_old.c", "archive/"};
    FzRanked out[2];
    u32 n;

    /*
     * The PATH completion source marks a directory by appending '/'.  A
     * bare last-slash basename scan gives "archive/" the EMPTY basename,
     * and the directory the user is typing toward then loses to every
     * file beside it.
     */
    n = yew_fz_rank("archive", 7U, entries, 2U, true, out);
    YEW_ASSERT_EQ_U64(n, 2U);
    YEW_ASSERT_EQ_STR(entries[out[0].idx], "archive/");
    YEW_ASSERT(out[0].score >= YEW_FZ_BASENAME_TIER);
}

void test_fuzzy_rank_empty_pattern_preserves_source_order(void)
{
    static const char *const items[] = {"zebra", "apple", "mango"};
    FzRanked out[3];
    u32 n;
    u32 i;

    /* Every candidate scores 1, so the stable sort must leave them in
     * the order the source produced -- which is what makes an unfiltered
     * menu show the source's own ordering. */
    n = yew_fz_rank("", 0U, items, 3U, false, out);
    YEW_ASSERT_EQ_U64(n, 3U);
    for (i = 0U; i < n; i++)
        YEW_ASSERT_EQ_U64(out[i].idx, i);
}

void test_fuzzy_handles_degenerate_input(void)
{
    FzRanked out[2];
    static const char *const with_null[] = {NULL, "abc"};

    YEW_ASSERT_EQ_I64(yew_fz_score(NULL, 3U, "abc", 3U, NULL),
                      YEW_FZ_NO_MATCH);
    YEW_ASSERT_EQ_I64(yew_fz_score("abc", 3U, NULL, 3U, NULL),
                      YEW_FZ_NO_MATCH);
    YEW_ASSERT_EQ_I64(yew_fz_score("", 0U, "", 0U, NULL), 1);
    YEW_ASSERT_EQ_I64(yew_fz_score("a", 1U, "", 0U, NULL),
                      YEW_FZ_NO_MATCH);
    YEW_ASSERT_EQ_U64(yew_fz_rank("a", 1U, NULL, 2U, false, out), 0U);
    YEW_ASSERT_EQ_U64(yew_fz_rank("a", 1U, with_null, 2U, false, NULL), 0U);
    /* A NULL candidate is skipped, not dereferenced. */
    YEW_ASSERT_EQ_U64(yew_fz_rank("a", 1U, with_null, 2U, false, out), 1U);
    YEW_ASSERT_EQ_U64(out[0].idx, 1U);
}

/*
 * Positions are u16.  Past 64 KiB of text a matched byte has no offset
 * that fits, so it must go UNRECORDED -- a truncated offset would
 * underline a byte 65536 positions earlier, and §5's highlighter walks
 * grapheme clusters from those offsets.  The score is unaffected: the
 * match is still a match, it just stops being highlightable, exactly as
 * it does past YEW_FZ_MAX_POS.
 */
void test_fuzzy_positions_past_64k_are_dropped_not_truncated(void)
{
    enum { LONG_LEN = 70000 };
    char *text = yew_xmalloc((size_t)LONG_LEN);
    FzMatch m;
    i32 score;

    (void)memset(text, 'x', (size_t)LONG_LEN);
    text[10] = 'a';
    text[LONG_LEN - 1] = 'b';
    score = yew_fz_score("ab", 2U, text, (u32)LONG_LEN, &m);
    YEW_ASSERT(score != YEW_FZ_NO_MATCH);
    YEW_ASSERT_EQ_U64(m.n_pos, 1U);
    YEW_ASSERT_EQ_U64(m.pos[0], 10U);
    /* The same text scored without the far byte keeps both positions,
     * proving the drop is about the OFFSET and not about the pattern. */
    text[70] = 'b';
    score = yew_fz_score("ab", 2U, text, (u32)LONG_LEN, &m);
    YEW_ASSERT(score != YEW_FZ_NO_MATCH);
    YEW_ASSERT_EQ_U64(m.n_pos, 2U);
    YEW_ASSERT_EQ_U64(m.pos[1], 70U);
    free(text);
}
