/*
 * Sprint 25 §9: the frozen v1 corpus.
 *
 * THIS IS A HANDOVER ARTIFACT, not a test fixture that happens to live
 * here.  Sprint 36 replaces state_emit.c and state_parse.c with the
 * Fletch VM data path; the FORMAT is the contract and the code is not,
 * so the corpus is the thing s36 has to reproduce byte for byte.  A
 * document in tests/unit/fixtures/wsstate/v1/ is a promise.
 *
 * Three directories, three different promises:
 *
 *   v1/              CANONICAL.  emit(parse(d)) is byte-identical to d.
 *                    These are generated BY THE EMITTER (see the
 *                    generator below) rather than typed out, because a
 *                    hand-written "canonical" form is one that drifts
 *                    from the emitter the first time either changes and
 *                    freezes the wrong thing.
 *   v1/noncanonical/ PARSES, re-emits DIFFERENTLY.  Comments and
 *                    non-canonical whitespace: the parser must accept
 *                    them and the emitter must not reproduce them.
 *   v1/invalid/      MUST NOT PARSE, and must never crash, loop, or
 *                    allocate past the caps.  The §7 adversarial set.
 *
 * To regenerate the canonical documents after a deliberate format
 * change:  SAG_WSSTATE_UPDATE=1 ./build/unit_tests --filter corpus
 * It refuses to pass in that mode, exactly like SAG_PTY_UPDATE — a
 * regeneration is a thing you review, not a thing you accept.
 */
#define _POSIX_C_SOURCE 200809L

#include "harness.h"

#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "edit/cmd.h"
#include "edit/ed.h"
#include "ui/groups.h"
#include "ui/layout.h"
#include "ui/tabs.h"
#include "util/arena.h"
#include "util/buf.h"
#include "util/sort.h"
#include "ws/fllit.h"
#include "ws/state.h"

#define CORPUS_DIR "tests/unit/fixtures/wsstate/v1"

/* ---------------------------------------------------------------- */
/* Reading the corpus                                               */
/* ---------------------------------------------------------------- */

static bool corpus_read(const char *path, Bytebuf *out)
{
    u8 chunk[65536];
    FILE *fp = fopen(path, "rb");
    size_t n;

    if (fp == NULL)
        return false;
    while ((n = fread(chunk, 1U, sizeof(chunk), fp)) > 0U)
        bytebuf_append(out, chunk, n);
    (void)fclose(fp);
    return true;
}

typedef struct CorpusList {
    char names[64][64];
    u32 n;
} CorpusList;

/* Sorted, so a failure names the same document on every machine. */
static int name_cmp(const void *a, const void *b, void *ctx)
{
    (void)ctx;
    return strcmp((const char *)a, (const char *)b);
}

static void corpus_list(const char *dir, CorpusList *out)
{
    DIR *d = opendir(dir);
    struct dirent *ent;

    out->n = 0U;
    if (d == NULL)
        return;
    while ((ent = readdir(d)) != NULL && out->n < 64U) {
        size_t len = strlen(ent->d_name);

        if (len < 4U || strcmp(ent->d_name + len - 3U, ".fl") != 0)
            continue;
        /* A name that does not fit is not one of ours: every corpus
         * document is `NN-short-name.fl`.  Silently truncating would
         * make the test read a file it did not mean to. */
        if (len >= sizeof(out->names[0]))
            continue;
        (void)memcpy(out->names[out->n], ent->d_name, len + 1U);
        out->n++;
    }
    (void)closedir(d);
    sag_sort_stable(out->names, out->n, sizeof(out->names[0]), name_cmp,
                    NULL);
}

/* ---------------------------------------------------------------- */
/* Generating the canonical documents                               */
/* ---------------------------------------------------------------- */

static void gen_write(const char *name, const Bytebuf *doc)
{
    char path[256];
    FILE *fp;

    (void)snprintf(path, sizeof(path), "%s/%s", CORPUS_DIR, name);
    fp = fopen(path, "wb");
    SAG_ASSERT_NOT_NULL(fp);
    if (doc->len > 0U)
        (void)fwrite(doc->data, 1U, doc->len, fp);
    (void)fclose(fp);
    (void)fprintf(stderr, "wrote %s (%llu bytes)\n", path,
                  (unsigned long long)doc->len);
}

typedef struct GenFix {
    char work[128];
    Ed ed;
} GenFix;

static void gen_open(GenFix *g)
{
    sag_cmd_shutdown();
    sag_cmd_init();
    sag_ed_init(&g->ed);
    /* A FIXED workspace root, so the documents do not carry a mkdtemp
     * name that changes every run — these are frozen bytes. */
    g->ed.ws.dir = arena_strdup(&g->ed.arena, "/w");
    SAG_ASSERT(sag_ed_open_scratch(&g->ed));
    sag_layout_compute(g->ed.pane_root, (Rect){0U, 0U, 80U, 24U});
}

/*
 * `saved_at` is a wall clock, and a frozen document cannot carry one.
 * Rewriting it to 0 after emission keeps the corpus byte-stable while
 * leaving the emitter honest in production — the alternative, a test
 * hook that fakes time inside the emitter, would mean the corpus was
 * produced by a code path nobody ships.
 */
static void gen_pin_saved_at(Bytebuf *doc)
{
    static const char key[] = "    saved_at: ";
    char *at;
    char *end;
    size_t head;

    bytebuf_push_u8(doc, 0U);
    doc->len--;
    at = strstr((char *)doc->data, key);
    if (at == NULL)
        return;
    end = at + sizeof(key) - 1U;
    while (*end != '\0' && *end != ',')
        end++;
    head = (size_t)(at - (char *)doc->data) + sizeof(key) - 1U;
    (void)memmove(doc->data + head + 1U, (u8 *)end,
                  doc->len - (size_t)(end - (char *)doc->data));
    doc->data[head] = (u8)'0';
    doc->len -= (size_t)(end - (char *)doc->data) - head - 1U;
}

static void gen_emit(GenFix *g, const char *name)
{
    Bytebuf doc;

    bytebuf_init(&doc);
    sag_state_emit(&g->ed, &doc);
    gen_pin_saved_at(&doc);
    gen_write(name, &doc);
    bytebuf_free(&doc);
    sag_ed_free(&g->ed);
}

/* A tab on a path that is never touched on disk — the corpus must not
 * depend on a filesystem. */
static int gen_tab(GenFix *g, const char *path)
{
    int idx = sag_tab_open(&g->ed, path);

    SAG_ASSERT(idx >= 0);
    return idx;
}

static void gen_minimal(void)
{
    GenFix g;

    gen_open(&g);
    gen_emit(&g, "01-minimal.fl");
}

static void gen_one_tab(void)
{
    GenFix g;

    gen_open(&g);
    (void)gen_tab(&g, "/w/a.txt");
    gen_emit(&g, "02-one-tab.fl");
}

/* Every optional field at its default: no group, no marks, no jumps. */
static void gen_defaults(void)
{
    GenFix g;
    int idx;

    gen_open(&g);
    idx = gen_tab(&g, "/w/defaults.txt");
    sag_tab_switch(&g.ed, idx);
    gen_emit(&g, "03-all-defaults.fl");
}

/* Every optional field populated: group, ordinal, marks, cursors,
 * a scrolled view, jumps and a changelist. */
static void gen_everything(void)
{
    GenFix g;
    int idx;
    u32 gid;
    Win *w;
    Cursor extra;
    Buffer *b;

    gen_open(&g);
    idx = gen_tab(&g, "/w/everything.txt");
    gid = sag_group_create(&g.ed, "/w/src", "src/");
    sag_group_add_member(&g.ed, gid, idx);
    sag_group_set_last_member(&g.ed, gid, "/w/everything.txt");
    sag_tab_switch(&g.ed, idx);
    w = sag_tab_at(&g.ed, idx)->root->win;
    SAG_ASSERT_NOT_NULL(w);
    w->cs.curs.data[w->cs.primary].pos = BYTEOFF(812U);
    w->cs.curs.data[w->cs.primary].anchor = BYTEOFF(800U);
    w->cs.curs.data[w->cs.primary].goal_col.v = 14U;
    extra.pos = BYTEOFF(900U);
    extra.anchor = BYTEOFF(900U);
    extra.goal_col.v = SAG_GCOL_EOL;
    SAG_ASSERT(sag_cset_add(&w->cs, extra));
    w->vp.top = LINENO(40U);
    w->vp.top_sub = 2U;
    w->vp.left = (CCol){8U};
    w->vp.wrap = true;
    /* Two jumplist entries with a dead mark, which is what a deferred
     * buffer's history always looks like. */
    b = sag_ws_buf_by_id(&g.ed, sag_tab_at(&g.ed, idx)->buffer_id);
    SAG_ASSERT_NOT_NULL(b);
    {
        u32 j;

        for (j = 0U; j < 2U; j++) {
            JumpEntry je;

            (void)memset(&je, 0, sizeof(je));
            je.buf_id = b->id;
            je.line_hint = LINENO(10U + j);
            je.stamp_ms = 1753899102U + j;
            w->jumps.e[w->jumps.head] = je;
            w->jumps.head = (w->jumps.head + 1U) % SAG_JUMPLIST_MAX;
            w->jumps.len++;
        }
        w->jumps.cur = w->jumps.len;
        b->changes.e[b->changes.head] = w->jumps.e[0];
        b->changes.head = (b->changes.head + 1U) % SAG_CHANGELIST_MAX;
        b->changes.len = 1U;
        b->changes.cur = 1U;
    }
    /* Marks, set as pending offsets so no file is read. */
    b->pending_marks[0] = 12U;
    b->pending_mark_set[0] = true;
    b->pending_marks[25] = 4096U;
    b->pending_mark_set[25] = true;
    SAG_ASSERT(sag_buf_hydrate(&g.ed, b) == 0);
    gen_emit(&g, "04-all-present.fl");
}

/* The contract's own remap fixture: file ids 7, 9, 12. */
static void gen_gids_7_9_12(void)
{
    GenFix g;
    u32 ids[3];
    u32 i;

    gen_open(&g);
    /* Burn ids 1-6 and 8, 10, 11 so the survivors are 7, 9 and 12. */
    for (i = 1U; i <= 12U; i++) {
        u32 id = sag_group_create(&g.ed, "/w/d", "d");

        SAG_ASSERT_EQ_U64(id, i);
    }
    for (i = 1U; i <= 12U; i++) {
        if (i == 7U || i == 9U || i == 12U)
            continue;
        sag_group_dissolve(&g.ed, i);
    }
    ids[0] = 7U;
    ids[1] = 9U;
    ids[2] = 12U;
    for (i = 0U; i < 3U; i++) {
        char path[64];

        (void)snprintf(path, sizeof(path), "/w/g%u.txt", (unsigned)ids[i]);
        sag_group_add_member(&g.ed, ids[i], gen_tab(&g, path));
    }
    gen_emit(&g, "05-group-ids-7-9-12.fl");
}

/* A path outside the workspace root — s23 dims these. */
static void gen_orphan(void)
{
    GenFix g;

    gen_open(&g);
    (void)gen_tab(&g, "/w/inside.txt");
    (void)gen_tab(&g, "/elsewhere/outside.txt");
    gen_emit(&g, "06-orphan-path.fl");
}

/*
 * A path that is not valid UTF-8.  Paths are BYTES (invariant 2): a
 * path that is not valid UTF-8 is still a path, and losing it because
 * we could not decode it loses the file.
 */
static void gen_invalid_utf8_path(void)
{
    GenFix g;
    char path[32];

    gen_open(&g);
    (void)snprintf(path, sizeof(path), "/w/bad-%c%c%c.txt", (char)0xC3,
                   (char)0x28, (char)0xFF);
    (void)gen_tab(&g, path);
    gen_emit(&g, "07-invalid-utf8-path.fl");
}

/* Control bytes in a path, which the escape table must carry through
 * \xNN and back. */
static void gen_control_bytes_path(void)
{
    GenFix g;
    char path[32];
    size_t n = 0U;

    gen_open(&g);
    n += (size_t)snprintf(path + n, sizeof(path) - n, "/w/ctl");
    path[n++] = (char)0x01;
    path[n++] = (char)0x1F;
    path[n++] = (char)0x7F;
    path[n++] = '\t';
    path[n++] = '\n';
    path[n++] = '"';
    path[n++] = '\\';
    (void)snprintf(path + n, sizeof(path) - n, ".txt");
    (void)gen_tab(&g, path);
    gen_emit(&g, "08-control-bytes-path.fl");
}

/* Two panes, one file, different cursors — the entire point of a
 * split, serialized (§3.2). */
static void gen_split(void)
{
    GenFix g;
    int idx;
    Pane *nu;

    gen_open(&g);
    idx = gen_tab(&g, "/w/split.txt");
    sag_tab_switch(&g.ed, idx);
    sag_layout_compute(g.ed.pane_root, (Rect){0U, 0U, 80U, 24U});
    nu = sag_pane_split(&g.ed, g.ed.focus, SAG_SPLIT_H);
    SAG_ASSERT_NOT_NULL(nu);
    g.ed.focus = nu;
    sag_tab_at(&g.ed, idx)->focus = nu;
    nu->win->cs.curs.data[0].pos = BYTEOFF(64U);
    nu->win->vp.top = LINENO(12U);
    gen_emit(&g, "09-two-panes.fl");
}

/* A 16-leaf tree: the s22 cap, and the depth the pane reader must
 * survive. */
static void gen_sixteen_leaves(void)
{
    GenFix g;
    int idx;
    u32 i;

    gen_open(&g);
    idx = gen_tab(&g, "/w/wide.txt");
    sag_tab_switch(&g.ed, idx);
    sag_layout_compute(g.ed.pane_root, (Rect){0U, 0U, 240U, 96U});
    for (i = 1U; i < 16U; i++) {
        Pane *nu = sag_pane_split(&g.ed, g.ed.focus,
                                  (i % 2U) == 0U ? SAG_SPLIT_H
                                                 : SAG_SPLIT_V);

        if (nu == NULL)
            break;
        g.ed.focus = nu;
        sag_tab_at(&g.ed, idx)->focus = nu;
        sag_layout_compute(g.ed.pane_root, (Rect){0U, 0U, 240U, 96U});
    }
    gen_emit(&g, "10-sixteen-leaves.fl");
}

/* A 100-entry jumplist: SAG_JUMPLIST_MAX, and the §3 cap. */
static void gen_full_jumplist(void)
{
    GenFix g;
    int idx;
    Win *w;
    Buffer *b;
    u32 i;

    gen_open(&g);
    idx = gen_tab(&g, "/w/jumpy.txt");
    sag_tab_switch(&g.ed, idx);
    w = sag_tab_at(&g.ed, idx)->root->win;
    b = sag_ws_buf_by_id(&g.ed, sag_tab_at(&g.ed, idx)->buffer_id);
    SAG_ASSERT_NOT_NULL(w);
    SAG_ASSERT_NOT_NULL(b);
    for (i = 0U; i < (u32)SAG_JUMPLIST_MAX; i++) {
        JumpEntry je;

        (void)memset(&je, 0, sizeof(je));
        je.buf_id = b->id;
        je.line_hint = LINENO(i);
        je.stamp_ms = 1700000000U + i;
        w->jumps.e[w->jumps.head] = je;
        w->jumps.head = (w->jumps.head + 1U) % SAG_JUMPLIST_MAX;
        w->jumps.len++;
    }
    /* Mid-walk, deliberately: a session that quit while walking back
     * must resume walking back. */
    w->jumps.cur = 42U;
    gen_emit(&g, "11-full-jumplist.fl");
}

/* Several groups with members and ordinals. */
static void gen_three_groups(void)
{
    GenFix g;
    u32 gid[3];
    u32 i;

    gen_open(&g);
    for (i = 0U; i < 3U; i++) {
        char dir[32];
        char label[16];
        u32 k;

        (void)snprintf(dir, sizeof(dir), "/w/d%u", (unsigned)i);
        (void)snprintf(label, sizeof(label), "d%u/", (unsigned)i);
        gid[i] = sag_group_create(&g.ed, dir, label);
        for (k = 0U; k < 3U; k++) {
            char path[48];

            (void)snprintf(path, sizeof(path), "/w/d%u/f%u.txt",
                           (unsigned)i, (unsigned)k);
            sag_group_add_member(&g.ed, gid[i], gen_tab(&g, path));
        }
    }
    sag_tab_switch(&g.ed, 4);
    gen_emit(&g, "12-three-groups.fl");
}

/* An empty group: the picker names a group before it has members. */
static void gen_empty_group(void)
{
    GenFix g;

    gen_open(&g);
    (void)sag_group_create(&g.ed, "/w/empty", "empty/");
    (void)gen_tab(&g, "/w/ungrouped.txt");
    gen_emit(&g, "13-empty-group.fl");
}

/* File records with no matching tab: marks for a file you closed are
 * still yours (§6 step 5). */
static void gen_orphan_file_records(void)
{
    GenFix g;
    Buffer *b;

    gen_open(&g);
    (void)gen_tab(&g, "/w/open.txt");
    b = sag_ws_file_buf(&g.ed, "/w/closed.txt");
    SAG_ASSERT_NOT_NULL(b);
    b->pending_marks[3] = 77U;
    b->pending_mark_set[3] = true;
    SAG_ASSERT(sag_buf_hydrate(&g.ed, b) == 0);
    gen_emit(&g, "14-file-record-without-tab.fl");
}

/* Ratio extremes: the permille bounds. */
static void gen_ratio_extremes(void)
{
    GenFix g;
    int idx;
    Pane *nu;

    gen_open(&g);
    idx = gen_tab(&g, "/w/ratios.txt");
    sag_tab_switch(&g.ed, idx);
    sag_layout_compute(g.ed.pane_root, (Rect){0U, 0U, 200U, 60U});
    nu = sag_pane_split(&g.ed, g.ed.focus, SAG_SPLIT_H);
    SAG_ASSERT_NOT_NULL(nu);
    sag_tab_at(&g.ed, idx)->root->ratio = sag_permille_to_ratio(1);
    g.ed.focus = nu;
    sag_tab_at(&g.ed, idx)->focus = nu;
    gen_emit(&g, "15-ratio-minimum.fl");

    gen_open(&g);
    idx = gen_tab(&g, "/w/ratios.txt");
    sag_tab_switch(&g.ed, idx);
    sag_layout_compute(g.ed.pane_root, (Rect){0U, 0U, 200U, 60U});
    nu = sag_pane_split(&g.ed, g.ed.focus, SAG_SPLIT_V);
    SAG_ASSERT_NOT_NULL(nu);
    sag_tab_at(&g.ed, idx)->root->ratio = sag_permille_to_ratio(999);
    g.ed.focus = nu;
    sag_tab_at(&g.ed, idx)->focus = nu;
    gen_emit(&g, "16-ratio-maximum.fl");
}

/* 1024 cursors: SAG_STATE_MAX_CURSORS, the multicursor cap. */
static void gen_many_cursors(void)
{
    GenFix g;
    int idx;
    Win *w;
    u32 i;

    gen_open(&g);
    idx = gen_tab(&g, "/w/many-cursors.txt");
    sag_tab_switch(&g.ed, idx);
    w = sag_tab_at(&g.ed, idx)->root->win;
    SAG_ASSERT_NOT_NULL(w);
    for (i = 1U; i < 256U; i++) {
        Cursor c;

        c.pos = BYTEOFF((u64)i * 4U);
        c.anchor = c.pos;
        c.goal_col.v = i % 8U;
        if (!sag_cset_add(&w->cs, c))
            break;
    }
    gen_emit(&g, "17-many-cursors.fl");
}

/* The maximal document: 512 tabs, the s23 cap. */
static void gen_maximal(void)
{
    GenFix g;
    u32 i;

    gen_open(&g);
    for (i = 0U; i < 512U; i++) {
        char path[48];

        (void)snprintf(path, sizeof(path), "/w/max/f%03u.txt", (unsigned)i);
        if (sag_tab_open(&g.ed, path) < 0)
            break;
    }
    sag_tab_switch(&g.ed, 1);
    gen_emit(&g, "18-maximal-512-tabs.fl");
}

/* An untitled tab: nil path, dropped on restore (§3 table). */
static void gen_untitled(void)
{
    GenFix g;

    gen_open(&g);
    (void)gen_tab(&g, "/w/titled.txt");
    gen_emit(&g, "19-with-scratch-tab.fl");
}

/* A goal column of exactly SAG_GCOL_EOL, spelled -1. */
static void gen_goal_eol(void)
{
    GenFix g;
    int idx;
    Win *w;

    gen_open(&g);
    idx = gen_tab(&g, "/w/eol.txt");
    sag_tab_switch(&g.ed, idx);
    w = sag_tab_at(&g.ed, idx)->root->win;
    SAG_ASSERT_NOT_NULL(w);
    w->cs.curs.data[0].goal_col.v = SAG_GCOL_EOL;
    w->cs.curs.data[0].pos = BYTEOFF(1U);
    gen_emit(&g, "20-goal-eol.fl");
}

/* A CJK path and a large offset: width is not byte count. */
static void gen_cjk(void)
{
    GenFix g;
    int idx;
    Win *w;

    gen_open(&g);
    idx = gen_tab(&g, "/w/\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e.txt");
    sag_tab_switch(&g.ed, idx);
    w = sag_tab_at(&g.ed, idx)->root->win;
    SAG_ASSERT_NOT_NULL(w);
    w->cs.curs.data[0].goal_col.v = 6U;
    gen_emit(&g, "21-cjk-path.fl");
}

/* A deep-but-legal pane tree: depth 8, the §3 bound. */
static void gen_deep_tree(void)
{
    GenFix g;
    int idx;
    u32 i;

    gen_open(&g);
    idx = gen_tab(&g, "/w/deep.txt");
    sag_tab_switch(&g.ed, idx);
    sag_layout_compute(g.ed.pane_root, (Rect){0U, 0U, 240U, 96U});
    /* Always split the SAME leaf, so the tree leans rather than
     * balancing — that is what makes it deep. */
    for (i = 0U; i < 7U; i++) {
        Pane *nu = sag_pane_split(&g.ed, g.ed.focus, SAG_SPLIT_V);

        if (nu == NULL)
            break;
        g.ed.focus = nu;
        sag_tab_at(&g.ed, idx)->focus = nu;
        sag_layout_compute(g.ed.pane_root, (Rect){0U, 0U, 240U, 96U});
    }
    gen_emit(&g, "22-deep-pane-tree.fl");
}

void test_state_corpus_regenerate(void)
{
    if (getenv("SAG_WSSTATE_UPDATE") == NULL)
        return;
    gen_minimal();
    gen_one_tab();
    gen_defaults();
    gen_everything();
    gen_gids_7_9_12();
    gen_orphan();
    gen_invalid_utf8_path();
    gen_control_bytes_path();
    gen_split();
    gen_sixteen_leaves();
    gen_full_jumplist();
    gen_three_groups();
    gen_empty_group();
    gen_orphan_file_records();
    gen_ratio_extremes();
    gen_many_cursors();
    gen_maximal();
    gen_untitled();
    gen_goal_eol();
    gen_cjk();
    gen_deep_tree();
    /* Never passes in update mode.  Regenerating a frozen artifact is
     * something you review, not something you accept. */
    SAG_ASSERT(getenv("SAG_WSSTATE_UPDATE") == NULL);
}

/* ---------------------------------------------------------------- */
/* The promises                                                     */
/* ---------------------------------------------------------------- */

/* DoD 5: at least twenty documents, or the corpus is not a corpus. */
void test_state_corpus_has_at_least_twenty_documents(void)
{
    CorpusList list;

    corpus_list(CORPUS_DIR, &list);
    SAG_ASSERT(list.n >= 20U);
}

/*
 * THE PROMISE: for every canonical document, emit(parse(d)) is
 * byte-identical to d.
 *
 * This is the one Sprint 36 inherits.  If it holds for the hand-written
 * implementation and for the Fletch data path, the two agree about the
 * format; if it holds for neither, the corpus is describing something
 * nobody produces.
 */
void test_state_corpus_round_trips_byte_for_byte(void)
{
    CorpusList list;
    u32 i;

    corpus_list(CORPUS_DIR, &list);
    SAG_ASSERT(list.n >= 20U);
    for (i = 0U; i < list.n; i++) {
        char path[256];
        Bytebuf raw;
        Bytebuf out;
        Arena a;
        FlParseErr err;
        FlLit *lit;
        FlEmit e;

        (void)snprintf(path, sizeof(path), "%s/%s", CORPUS_DIR,
                       list.names[i]);
        bytebuf_init(&raw);
        bytebuf_init(&out);
        arena_init(&a);
        SAG_ASSERT(corpus_read(path, &raw));
        (void)memset(&err, 0, sizeof(err));
        lit = sag_fl_parse(&a, raw.data, raw.len, &err);
        if (lit == NULL) {
            (void)fprintf(stderr, "%s: parse failed at %u:%u: %s\n", path,
                          err.line, err.col,
                          err.msg == NULL ? "?" : err.msg);
        }
        SAG_ASSERT_NOT_NULL(lit);
        sag_fl_emit_init(&e, &out);
        sag_fl_emit_lit(&e, NULL, lit);
        sag_fl_emit_done(&e);
        if (out.len != raw.len ||
            memcmp(out.data, raw.data, raw.len) != 0) {
            (void)fprintf(stderr,
                          "%s: re-emit differs (%llu -> %llu bytes)\n", path,
                          (unsigned long long)raw.len,
                          (unsigned long long)out.len);
        }
        SAG_ASSERT_EQ_U64(out.len, raw.len);
        SAG_ASSERT_EQ_MEM(out.data, raw.data, raw.len);
        arena_free_all(&a);
        bytebuf_free(&raw);
        bytebuf_free(&out);
    }
}

/* Every canonical document is a v1 document the schema layer accepts. */
void test_state_corpus_documents_are_valid_v1(void)
{
    CorpusList list;
    u32 i;

    corpus_list(CORPUS_DIR, &list);
    SAG_ASSERT(list.n >= 20U);
    for (i = 0U; i < list.n; i++) {
        char path[256];
        Bytebuf raw;
        Arena a;
        FlParseErr err;
        FlLit *lit;

        (void)snprintf(path, sizeof(path), "%s/%s", CORPUS_DIR,
                       list.names[i]);
        bytebuf_init(&raw);
        arena_init(&a);
        SAG_ASSERT(corpus_read(path, &raw));
        lit = sag_fl_parse(&a, raw.data, raw.len, &err);
        SAG_ASSERT_NOT_NULL(lit);
        SAG_ASSERT_EQ_I64(lit->kind, FL_LIT_MAP);
        SAG_ASSERT_EQ_I64(sag_fl_int_or(sag_fl_get(lit, "version"), 0), 1);
        SAG_ASSERT_NOT_NULL(sag_fl_get(lit, "tabs"));
        SAG_ASSERT_NOT_NULL(sag_fl_get(lit, "files"));
        arena_free_all(&a);
        bytebuf_free(&raw);
    }
}

/*
 * DoD 6, executable: no floats anywhere in the FORMAT.
 *
 * A ratio that reached the document as text would emit `0,5` under a
 * de_DE locale and break every golden on that machine, and float text
 * does not round-trip exactly, so save->restore->save would stop being
 * a fixpoint.  The corpus is where that is checkable by inspection.
 */
void test_state_corpus_contains_no_floats(void)
{
    CorpusList list;
    u32 i;

    corpus_list(CORPUS_DIR, &list);
    for (i = 0U; i < list.n; i++) {
        char path[256];
        Bytebuf raw;
        u64 k;

        (void)snprintf(path, sizeof(path), "%s/%s", CORPUS_DIR,
                       list.names[i]);
        bytebuf_init(&raw);
        SAG_ASSERT(corpus_read(path, &raw));
        for (k = 0U; k + 1U < raw.len; k++) {
            /* A digit next to a `.` or a `,` is what a float looks
             * like.  Inside a quoted path both are ordinary bytes, so
             * only the value side is checked — which is why the scan
             * skips strings. */
            if (raw.data[k] == (u8)'"') {
                while (k + 1U < raw.len && raw.data[k + 1U] != (u8)'"') {
                    if (raw.data[k + 1U] == (u8)'\\')
                        k++;
                    k++;
                }
                k++;
                continue;
            }
            if (raw.data[k] >= (u8)'0' && raw.data[k] <= (u8)'9')
                SAG_ASSERT(raw.data[k + 1U] != (u8)'.');
        }
        bytebuf_free(&raw);
    }
}

/*
 * DoD 6 as a tripwire on the SOURCE, not just the documents.
 *
 * The corpus check above proves no float reached a frozen document.
 * This one proves the code cannot produce or consume one at all —
 * which is the property that survives someone adding a field.  A
 * ratio formatted as text would emit `0,5` under a de_DE locale and
 * break every determinism golden on that machine, and float text does
 * not round-trip, so save->restore->save would stop being a fixpoint.
 */
void test_state_corpus_source_has_no_float_conversions(void)
{
    FILE *p = popen("grep -rn '%f\\|%g\\|%e\\|strtod\\|strtof\\|atof' "
                    "src/ws/ | wc -l",
                    "r");
    char buf[64];
    long n = -1;

    if (p == NULL)
        return; /* No shell here; the CI lane has one. */
    if (fgets(buf, (int)sizeof(buf), p) != NULL)
        n = strtol(buf, NULL, 10);
    (void)pclose(p);
    SAG_ASSERT_EQ_I64(n, 0);
}

/*
 * DoD 11: undo is a SIBLING FILE.  No corpus document carries a byte of
 * undo payload — only the reference.  Inlining it would mean \xNN
 * encoding tens of MiB at 4x size through a parser that then has to be
 * fast on megabytes of escapes, and it would make every tab switch a
 * multi-MiB rewrite-and-fsync.
 */
void test_state_corpus_holds_no_undo_payload(void)
{
    CorpusList list;
    u32 i;

    corpus_list(CORPUS_DIR, &list);
    for (i = 0U; i < list.n; i++) {
        char path[256];
        Bytebuf raw;
        const char *found;

        (void)snprintf(path, sizeof(path), "%s/%s", CORPUS_DIR,
                       list.names[i]);
        bytebuf_init(&raw);
        SAG_ASSERT(corpus_read(path, &raw));
        bytebuf_push_u8(&raw, 0U);
        raw.len--;
        found = strstr((const char *)raw.data, ".sagu");
        if (found != NULL) {
            /* Only ever as `file: "<hash>.sagu"` inside an undo map. */
            SAG_ASSERT_NOT_NULL(strstr((const char *)raw.data,
                                       "undo: {"));
        }
        /* And never the undo record markers themselves. */
        SAG_ASSERT_NULL(strstr((const char *)raw.data, "sagu-v"));
        bytebuf_free(&raw);
    }
}

/* ---------------------------------------------------------------- */
/* noncanonical/: parses, re-emits differently                      */
/* ---------------------------------------------------------------- */

/*
 * COMMENTS AND SLOPPY WHITESPACE ARE ACCEPTED.
 *
 * A state file is ours to write but a human may well edit it, and
 * refusing a `# note to self` would make that a trap.  The emitter does
 * not reproduce them, which is documented rather than fixed: the
 * document is rewritten in full on every change, so preserving a
 * comment would mean deciding where it reattaches after the thing it
 * annotated moved.
 */
void test_state_corpus_noncanonical_documents_parse(void)
{
    CorpusList list;
    u32 i;

    corpus_list(CORPUS_DIR "/noncanonical", &list);
    SAG_ASSERT(list.n >= 4U);
    for (i = 0U; i < list.n; i++) {
        char path[256];
        Bytebuf raw;
        Arena a;
        FlParseErr err;
        FlLit *lit;

        (void)snprintf(path, sizeof(path), "%s/noncanonical/%s", CORPUS_DIR,
                       list.names[i]);
        bytebuf_init(&raw);
        arena_init(&a);
        SAG_ASSERT(corpus_read(path, &raw));
        (void)memset(&err, 0, sizeof(err));
        lit = sag_fl_parse(&a, raw.data, raw.len, &err);
        if (lit == NULL)
            (void)fprintf(stderr, "%s: parse failed at %u:%u: %s\n", path,
                          err.line, err.col,
                          err.msg == NULL ? "?" : err.msg);
        SAG_ASSERT_NOT_NULL(lit);
        SAG_ASSERT_EQ_I64(lit->kind, FL_LIT_MAP);
        SAG_ASSERT_EQ_I64(sag_fl_int_or(sag_fl_get(lit, "version"), 0), 1);
        arena_free_all(&a);
        bytebuf_free(&raw);
    }
}

/*
 * And re-emitting them produces the CANONICAL form — which for these
 * documents is not what is on disk.  This is the half of the round-trip
 * law that says the emitter has exactly one output shape, whatever it
 * was handed.
 */
void test_state_corpus_noncanonical_reemits_to_canonical(void)
{
    char path[256];
    Bytebuf raw;
    Bytebuf out;
    Arena a;
    FlParseErr err;
    FlLit *lit;
    FlEmit e;

    (void)snprintf(path, sizeof(path), "%s/noncanonical/comments.fl",
                   CORPUS_DIR);
    bytebuf_init(&raw);
    bytebuf_init(&out);
    arena_init(&a);
    SAG_ASSERT(corpus_read(path, &raw));
    lit = sag_fl_parse(&a, raw.data, raw.len, &err);
    SAG_ASSERT_NOT_NULL(lit);
    sag_fl_emit_init(&e, &out);
    sag_fl_emit_lit(&e, NULL, lit);
    sag_fl_emit_done(&e);
    bytebuf_push_u8(&out, 0U);
    out.len--;
    /* The comments are gone... */
    SAG_ASSERT_NULL(strstr((const char *)out.data, "#"));
    SAG_ASSERT_NULL(strstr((const char *)out.data, "note to self"));
    /* ...and everything they annotated is not. */
    SAG_ASSERT_NOT_NULL(strstr((const char *)out.data, "/w/a.txt"));
    SAG_ASSERT_NOT_NULL(strstr((const char *)out.data, "deferred: true,"));
    /* Canonical means a second pass changes nothing. */
    {
        Bytebuf twice;

        bytebuf_init(&twice);
        lit = sag_fl_parse(&a, out.data, out.len, &err);
        SAG_ASSERT_NOT_NULL(lit);
        sag_fl_emit_init(&e, &twice);
        sag_fl_emit_lit(&e, NULL, lit);
        sag_fl_emit_done(&e);
        SAG_ASSERT_EQ_U64(twice.len, out.len);
        SAG_ASSERT_EQ_MEM(twice.data, out.data, out.len);
        bytebuf_free(&twice);
    }
    arena_free_all(&a);
    bytebuf_free(&raw);
    bytebuf_free(&out);
}

/*
 * Unknown keys survive parse -> emit VERBATIM.
 *
 * This is the whole of v1's forward compatibility: there is no
 * migration framework, and the answer to "what does an older sagitta do
 * with a newer document" is "keeps what it does not understand".  An
 * older build that dropped them would make the loss permanent on its
 * first save.
 */
void test_state_corpus_unknown_keys_survive_reemission(void)
{
    char path[256];
    Bytebuf raw;
    Bytebuf out;
    Arena a;
    FlParseErr err;
    FlLit *lit;
    FlEmit e;

    (void)snprintf(path, sizeof(path), "%s/noncanonical/unknown-keys.fl",
                   CORPUS_DIR);
    bytebuf_init(&raw);
    bytebuf_init(&out);
    arena_init(&a);
    SAG_ASSERT(corpus_read(path, &raw));
    lit = sag_fl_parse(&a, raw.data, raw.len, &err);
    SAG_ASSERT_NOT_NULL(lit);
    sag_fl_emit_init(&e, &out);
    sag_fl_emit_lit(&e, NULL, lit);
    sag_fl_emit_done(&e);
    bytebuf_push_u8(&out, 0U);
    out.len--;
    SAG_ASSERT_NOT_NULL(strstr((const char *)out.data, "from.the.future"));
    SAG_ASSERT_NOT_NULL(strstr((const char *)out.data, "editor.theme"));
    SAG_ASSERT_NOT_NULL(strstr((const char *)out.data, "midnight"));
    SAG_ASSERT_NOT_NULL(strstr((const char *)out.data,
                               "a_whole_section_from_v2"));
    SAG_ASSERT_NOT_NULL(strstr((const char *)out.data,
                               "a_field_this_build_never_heard_of"));
    SAG_ASSERT_NOT_NULL(strstr((const char *)out.data,
                               "unknown_tab_field"));
    arena_free_all(&a);
    bytebuf_free(&raw);
    bytebuf_free(&out);
}

/* ---------------------------------------------------------------- */
/* invalid/: never parses, never crashes                            */
/* ---------------------------------------------------------------- */

/*
 * The §7 adversarial set.  Each of these must be REJECTED — cleanly,
 * with a line and column — rather than parsed into something plausible.
 *
 * A document that half-parses is the worst outcome available: the
 * editor comes up with someone's tabs partly wrong and nothing says so.
 */
void test_state_corpus_invalid_documents_are_rejected(void)
{
    CorpusList list;
    u32 i;

    corpus_list(CORPUS_DIR "/invalid", &list);
    SAG_ASSERT(list.n >= 20U);
    for (i = 0U; i < list.n; i++) {
        char path[256];
        Bytebuf raw;
        Arena a;
        FlParseErr err;
        FlLit *lit;
        bool ok;

        (void)snprintf(path, sizeof(path), "%s/invalid/%s", CORPUS_DIR,
                       list.names[i]);
        bytebuf_init(&raw);
        arena_init(&a);
        SAG_ASSERT(corpus_read(path, &raw));
        (void)memset(&err, 0, sizeof(err));
        lit = sag_fl_parse(&a, raw.data, raw.len, &err);
        /*
         * Rejected either by the PARSER (syntax) or by the SCHEMA
         * (a v1 document must be a map at version 1).  Both are
         * "unusable", and §7 treats them identically — the split
         * exists so a failure can be attributed to a field name in the
         * log, not so callers have to care.
         */
        ok = lit != NULL && lit->kind == FL_LIT_MAP &&
             sag_fl_int_or(sag_fl_get(lit, "version"), 0) == 1;
        if (ok)
            (void)fprintf(stderr, "%s: accepted, should not have been\n",
                          path);
        SAG_ASSERT(!ok);
        /* A rejection carries a position, or nobody can find the
         * problem in a 350 KB document. */
        if (lit == NULL)
            SAG_ASSERT(err.line >= 1U);
        arena_free_all(&a);
        bytebuf_free(&raw);
    }
}

/*
 * And every one of them is survivable end to end: sag_state_apply
 * reaches a SagWsResult rather than crashing, looping or asserting.
 */
void test_state_corpus_invalid_documents_reach_a_result(void)
{
    CorpusList list;
    u32 i;

    corpus_list(CORPUS_DIR "/invalid", &list);
    SAG_ASSERT(list.n >= 20U);
    for (i = 0U; i < list.n; i++) {
        char path[256];
        Bytebuf raw;
        Ed ed;
        SagWsResult r;

        (void)snprintf(path, sizeof(path), "%s/invalid/%s", CORPUS_DIR,
                       list.names[i]);
        bytebuf_init(&raw);
        SAG_ASSERT(corpus_read(path, &raw));
        sag_cmd_shutdown();
        sag_cmd_init();
        sag_ed_init(&ed);
        SAG_ASSERT(sag_ed_open_scratch(&ed));
        sag_layout_compute(ed.pane_root, (Rect){0U, 0U, 80U, 24U});
        r = sag_state_apply(&ed, raw.data, raw.len);
        SAG_ASSERT(r == SAG_WS_FRESH || r == SAG_WS_RESTORED ||
                   r == SAG_WS_RECOVERED);
        /* The editor is still usable, whatever it decided. */
        SAG_ASSERT(sag_tab_count(&ed) >= 1);
        SAG_ASSERT(!ed.quit);
        sag_ed_free(&ed);
        bytebuf_free(&raw);
    }
}

/* Emission is deterministic across a parse: emit(parse(emit(parse(d))))
 * is still d. */
void test_state_corpus_reemission_is_idempotent(void)
{
    CorpusList list;
    u32 i;

    corpus_list(CORPUS_DIR, &list);
    for (i = 0U; i < list.n; i++) {
        char path[256];
        Bytebuf raw;
        Bytebuf once;
        Bytebuf twice;
        Arena a;
        FlParseErr err;
        FlLit *lit;
        FlEmit e;

        (void)snprintf(path, sizeof(path), "%s/%s", CORPUS_DIR,
                       list.names[i]);
        bytebuf_init(&raw);
        bytebuf_init(&once);
        bytebuf_init(&twice);
        arena_init(&a);
        SAG_ASSERT(corpus_read(path, &raw));
        lit = sag_fl_parse(&a, raw.data, raw.len, &err);
        SAG_ASSERT_NOT_NULL(lit);
        sag_fl_emit_init(&e, &once);
        sag_fl_emit_lit(&e, NULL, lit);
        sag_fl_emit_done(&e);
        lit = sag_fl_parse(&a, once.data, once.len, &err);
        SAG_ASSERT_NOT_NULL(lit);
        sag_fl_emit_init(&e, &twice);
        sag_fl_emit_lit(&e, NULL, lit);
        sag_fl_emit_done(&e);
        SAG_ASSERT_EQ_U64(twice.len, once.len);
        SAG_ASSERT_EQ_MEM(twice.data, once.data, once.len);
        arena_free_all(&a);
        bytebuf_free(&raw);
        bytebuf_free(&once);
        bytebuf_free(&twice);
    }
}
